<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="" />
        <span class="zdt-toolbar-info">Cache Data</span>
    </div>
    <div class="zdt-toolbar-detail zdt-toolbar-detail-overflow">
        <span class="zdt-toolbar-info zdt-toolbar-info-heading">
            <a href="#" target="_blank">
                DoctrineCacheToolbar
            </a>
        </span>
        <div class="zdt-toolbar-info">
            <?php $data = $collector->getCacheStats(); ?>
            <span class="zdt-detail-label">Total</span>
            <div class="zdt-detail-context">
                <strong>Put: </strong><?php echo $data['cache-toolbar']['total']['put']; ?> <br>
                <strong>Hit: </strong><?php echo $data['cache-toolbar']['total']['hit']; ?> <br>
                <strong>Miss: </strong><?php echo $data['cache-toolbar']['total']['miss']; ?> <br>
            </div>
        </div>
    </div>
</div>