<div class="zdt-toolbar-entry">
    <div class="zdt-toolbar-preview">
        <img src="" />
        <span class="zdt-toolbar-info">Cache Data</span>
    </div>
    <div class="zdt-toolbar-detail zdt-toolbar-detail-overflow">
        <div class="zdt-toolbar-info">
            <?php $data = $collector->getCacheStats(); ?>
            <p>Total:</p>
            <span><?php echo $data['cache-toolbar']['total']['put']; ?></span>
            <span><?php echo $data['cache-toolbar']['total']['hit']; ?></span>
            <span><?php echo $data['cache-toolbar']['total']['miss']; ?></span>
        </div>
    </div>
</div>